# Generated by Django 5.2 on 2025-05-04 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='beneficiario',
            old_name='nombre',
            new_name='alias',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nro_cuenta',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='nro_cuenta',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ci',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='beneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.cuenta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
