# Generated by Django 5.2 on 2025-05-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_beneficiario_beneficiario_alter_cuenta_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='nro_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
