# Generated by Django 5.2 on 2025-05-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cuenta_nro_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='beneficiario',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nro_cuenta',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
