# Generated by Django 5.2 on 2025-05-04 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_beneficiario_beneficiario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='beneficiario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='beneficiado_por', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
